// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace StarInventoryAPI.Migrations
{
    [DbContext(typeof(ItemCacheDb))]
    [Migration("20251101002519_CacheStufff")]
    partial class CacheStufff
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("StarItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsSharedWithOrganization")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("UexIdentifier")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PersonalItems");
                });

            modelBuilder.Entity("StarLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UexIdentifier")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("StarLocations");
                });

            modelBuilder.Entity("UexCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DateAdded")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "date_added");

                    b.Property<int>("DateModified")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "date_modified");

                    b.Property<int>("IsGameRelated")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "is_game_related");

                    b.Property<int>("IsMining")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "is_mining");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "section");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "type");

                    b.HasKey("Id");

                    b.ToTable("UexCategories");
                });

            modelBuilder.Entity("UexItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("longtext");

                    b.Property<string>("CompanyName")
                        .HasColumnType("longtext");

                    b.Property<int>("DateAdded")
                        .HasColumnType("int");

                    b.Property<int>("DateModified")
                        .HasColumnType("int");

                    b.Property<string>("GameVersion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Notification")
                        .HasColumnType("longtext");

                    b.Property<string>("Section")
                        .HasColumnType("longtext");

                    b.Property<string>("Size")
                        .HasColumnType("longtext");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StoreUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("VehicleName")
                        .HasColumnType("longtext");

                    b.Property<int>("categoryId")
                        .HasColumnType("int");

                    b.Property<bool>("is_commodity")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("is_exclusive_concierge")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("is_exclusive_pledge")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("is_exclusive_subscriber")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("is_harvestable")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("parentId")
                        .HasColumnType("int");

                    b.Property<string>("uuid")
                        .HasColumnType("longtext");

                    b.Property<int>("vehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UexItem");
                });
#pragma warning restore 612, 618
        }
    }
}
